/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class how_monero_hodl_jni_CryptoOpsUtil */

#ifndef _Included_how_monero_hodl_jni_CryptoOpsUtil
#define _Included_how_monero_hodl_jni_CryptoOpsUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     how_monero_hodl_jni_CryptoOpsUtil
 * Method:    scalarMult
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_how_monero_hodl_jni_CryptoOpsUtil_scalarMult
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     how_monero_hodl_jni_CryptoOpsUtil
 * Method:    doubleScalarMultBaseVartime
 * Signature: ([B[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_how_monero_hodl_jni_CryptoOpsUtil_doubleScalarMultBaseVartime
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
